name: Bug Report
description: Report a bug or issue with Tree-Sitter MCP
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Use these parameters '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: usage
    attributes:
      label: Usage Mode
      description: How are you using Tree-Sitter MCP?
      options:
        - CLI tool
        - MCP server with Claude Desktop
        - MCP server with other client
        - npm package in code
    validations:
      required: true

  - type: input
    id: command
    attributes:
      label: Command/Tool Used
      description: The specific command or MCP tool you were using
      placeholder: "e.g., tree-sitter-mcp search 'function' or search_code tool"

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your system information
      value: |
        - OS: [e.g., macOS 14.0, Windows 11, Ubuntu 22.04]
        - Node.js version: [e.g., 18.17.0]
        - Package version: [e.g., 2.0.0]
        - Project type: [e.g., TypeScript React app, Python Django project]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: sample-code
    attributes:
      label: Sample Code/Files
      description: If relevant, provide sample code that triggers the bug
      placeholder: |
        ```typescript
        // Sample code that causes the issue
        function example() {
          return "problematic code";
        }
        ```

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages or logs (use debug mode with TREE_SITTER_MCP_DEBUG=true)
      placeholder: |
        ```
        Paste error logs here...
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Screenshots, related issues, workarounds you've tried, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues to avoid creating a duplicate
          required: true
        - label: I am using the latest version of Tree-Sitter MCP
          required: true
        - label: I have provided all the information requested above
          required: true